//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol
    {
        public rol()
        {
            this.permiso = new HashSet<permiso>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int idRol { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<permiso> permiso { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
